%  LaTeX support: latex@mdpi.com 
%  In case you need support, please attach all files that are necessary for compiling as well as the log file, and specify the details of your LaTeX setup (which operating system and LaTeX version / tools you are using).


<<setup-knitr, cache=FALSE, include=FALSE>>=
library(knitr)

# To update the references when compiling the pdf run the following code in the 
# console: knitr::knit2pdf("LightingPaper2020.rnw")

# Set default knitr options for chunks.
opts_chunk$set(
  # ********************************************************
  eval = TRUE,
  include = TRUE,
  echo = FALSE, 
  warning = FALSE,
  self.contained = FALSE
  # ********************************************************
)
@


<<setup-R, include=FALSE>>=
library(dplyr)
library(forcats)
library(ggplot2)
library(ggspectra)
library(magrittr)
library(MESS)
library(MKHthemes)
library(readxl)
library(rlist)
library(tibble)
library(tidyr)
library(xtable)
@


<<setup-graphs, include=FALSE>>=
# This variable switches the cache on/off for all R code chunks that are configured for cacheing.
# Set to FALSE if some plots are not updating as expected, then set back to TRUE.
use_cache <- TRUE

# Here are some options for the colors to use in the ggspectra graphs.
# The variable chroma_type is used in all graphs,
# so changing the value of chroma_type here will change all graphs at once,
# although you may need to be careful about cacheing.
# The argument cache.extra=openssl::md5(chroma_type) is supposed to trigger a rebuild of graphs 
# when the value of chroma_type changes.

# chroma_type <- photobiology::cone_fundamentals10.spct    # Color shifted: yellow/red at 555 nm

# Linear energy luminous efficiency functions
# chroma_type <- photobiology::ciev2.spct                  # fails to plot data
# chroma_type <- photobiology::ciev10.spct                 # fails to plot data

# CIE Chromacity co-ordinates
# chroma_type <- photobiology::ciexyzCC2.spct              # Only RGB
# chroma_type <- photobiology::ciexyzCC10.spct             # Only RGB, but red extends to 750nm

# CIE Color matching functions
# chroma_type <- photobiology::ciexyzCMF2.spct             # Very similar to "CMF" (maybe same?)
chroma_type <- photobiology::ciexyzCMF10.spct            # Very similar to "CMF" (maybe same?)

# chroma_type <- "CC"                                      # Wide, but has no yellow (only R, G, B)
# chroma_type <- "CMF"                                     # Narrow, but gives yellows

@


% The helpful information at 
% https://nuanceabounds.org/fix-latex-package-option-clash-error-passoptionstopackage/
% indicates the \PassOptionsToPackage command must occur BEFORE the \documentclass command.
\PassOptionsToPackage{inline}{enumitem}

%=================================================================
\documentclass[energies,article,submit,moreauthors,pdftex]{Definitions/mdpi} 

% If you would like to post an early version of this manuscript as a preprint, you may use preprint as the journal and change 'submit' to 'accept'. The document class line would be, e.g., \documentclass[preprints,article,accept,moreauthors,pdftex]{mdpi}. This is especially recommended for submission to arXiv, where line numbers should be removed before posting. For preprints.org, the editorial staff will make this change immediately prior to posting.

%--------------------
% Class Options:
%--------------------
%----------
% journal
%----------
% Choose between the following MDPI journals:
% energies, entropy, environments, 
% 
%---------
% article
%---------
% The default type of manuscript is "article", but can be replaced by: 
% abstract, addendum, article, benchmark, book, bookreview, briefreport, casereport, 
% changes, comment, commentary, communication, conceptpaper, conferenceproceedings, 
% correction, conferencereport, expressionofconcern, extendedabstract, meetingreport, 
% creative, datadescriptor, discussion, editorial, essay, erratum, hypothesis, 
% interestingimages, letter, meetingreport, newbookreceived, obituary, opinion, 
% projectreport, reply, retraction, review, perspective, protocol, shortnote, 
% supfile, technicalnote, viewpoint
% supfile = supplementary materials

%----------
% submit
%----------
% The class option "submit" will be changed to "accept" by the Editorial Office when the paper is accepted. 
% This will only make changes to the frontpage (e.g., the logo of the journal will get visible), 
% the headings, and the copyright information. 
% Also, line numbering will be removed. 
% Journal info and pagination for accepted papers will also be assigned by the Editorial Office.

%------------------
% moreauthors
%------------------
% If there is only one author the class option oneauthor should be used. 
% Otherwise use the class option moreauthors.

%---------
% pdftex
%---------
% The option pdftex is for use with pdfLaTeX. 
% If eps figures are used, remove the option pdftex and use LaTeX and dvi2pdf.


%=================================================================
\firstpage{1} 
\makeatletter 
\setcounter{page}{\@firstpage} 
\makeatother
\pubvolume{xx}
\issuenum{1}
\articlenumber{5}
\pubyear{2020}
\copyrightyear{2020}
%\externaleditor{Academic Editor: name}
\history{Received: date; Accepted: date; Published: date}
%\updates{yes} % If there is an update available, un-comment this line

%% MDPI internal command: uncomment if new journal that already uses continuous page numbers 
%\continuouspages{yes}

%------------------------------------------------------------------
% The following line should be uncommented if the LaTeX file is uploaded to arXiv.org
%\pdfoutput=1

%=================================================================
% Add packages and commands here. The following packages are loaded in our class file: 
% fontenc, inputenc, calc, indentfirst, fancyhdr, graphicx,epstopdf, lastpage, 
% ifthen, lineno, float, amsmath, setspace, enumitem, mathpazo, booktabs, titlesec, 
% etoolbox, tabto, xcolor, soul, multirow, microtype, tikz, totcount, amsthm, 
% hyphenat, natbib, hyperref, footmisc, url, geometry, newfloat, caption

\usetikzlibrary{arrows,positioning}         % For diagrams with tikz
\usepackage{booktabs}                       % For nice table rules
\usepackage[makeroom]{cancel}               % To show terms go to zero
\usepackage{pdflscape}                      % For landscape environment \begin{landscape} ... \end{landscape}
\usepackage{subcaption}                     % For Figure 12 (a), Figure 12 (b), etc.
\usetikzlibrary{decorations.pathreplacing,angles,quotes}


%=================================================================
%% Please use the following mathematics environments: 
%% Theorem, Lemma, Corollary, Proposition, Characterization, Property, 
%% Problem, Example, ExamplesandDefinitions, Hypothesis, Remark, 
%% Definition, Notation, Assumption
%% For proofs, please use the proof environment 
%% (the amsthm package is loaded by the MDPI class).


% Author macros
\input{pieces/macros.tex}


%=================================================================
% Full title of the paper (Capitalized)
\Title{The Energy and Exergy of Light With Application to Societal Exergy Analysis} % for illumination


% Author Orchid ID: enter ID or remove command

% Matt
\newcommand{\orcidauthorA}{0000-0002-7438-214X} % Add \orcidA{} behind the author's name
% Zeke
\newcommand{\orcidauthorB}{0000-0001-9260-7827} % Add \orcidB{} behind the author's name
% Emmanuel
\newcommand{\orcidauthorC}{0000-0002-5964-6776} % Add \orcidC{} behind the author's name
% Paul
\newcommand{\orcidauthorD}{0000-0001-6925-8040} % Add \orcidD{} behind the author's name


% Authors, for the paper (add full first names)
\Author{Matthew Kuperus Heun $^{1}$*\orcidA{}, 
        Zeke Marshall $^{2}$\orcidB{}, 
        Emmanuel Aramendia $^{2}$\orcidC{}, and 
        Paul E. Brockway $^{2}$\orcidD{}}


% Authors, for metadata in PDF
\AuthorNames{Matthew Kuperus Heun, Zeke Marshall, Emmanuel Aramendia, and Paul E. Brockway}


% Affiliations / Addresses (Add [1] after \address if there is only one affiliation.)
\address{%
$^{1}$ \quad Department of Engineering, 
             Calvin University, 3201 Burton St.\ SE, Grand Rapids, MI, 49546, USA\\
$^{2}$ \quad Sustainability Research Institute, School of Earth and Environment, 
             University of Leeds, Leeds LS2 9JT, United Kingdom}


% Contact information of the corresponding author
\corres{Correspondence: mkh2@calvin.edu; Tel.: +1 (616) 526-6663}


% Current address and/or shared authorship
% \firstnote{Current address: Affiliation 3} 
% \secondnote{These authors contributed equally to this work.}
% The commands \thirdnote{} till \eighthnote{} are available for further notes

%\simplesumm{} % Simple summary

%\conference{} % An extended version of a conference paper


% Abstract (Do not insert blank lines, i.e. \\) 
\abstract{
% A single paragraph of about 200 words maximum. 
% For research articles, abstracts should give a pertinent overview of the work.
% We strongly encourage authors to use the following style of structured abstracts, 
% but without headings: 
% (1) Background: Place the question addressed in a broad context 
% and highlight the purpose of the study; 
% (2) Methods: Describe briefly the main methods or treatments applied; 
% (3) Results: Summarize the article's main findings; and 
% (4) Conclusion: Indicate the main conclusions or interpretations. 
% The abstract should be an objective representation of the article, 
% it must not contain results which are not presented and substantiated 
% in the main text and should not exaggerate the main conclusions.
**** Add abstract. ****
}

% Keywords
\keyword{
% (list three to ten pertinent keywords specific to the article, yet reasonably common within the subject discipline.)
keyword 1; keyword 2; keyword 3
}

% The fields PACS, MSC, and JEL may be left empty or commented out if not applicable
%\PACS{J0101}
%\MSC{}
%\JEL{}


%\datasetlicense{license under which the data set is made available (CC0, CC-BY, CC-BY-SA, CC-BY-NC, etc.)}


%\setcounter{secnumdepth}{4}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \setcounter{section}{-1} %% Remove this when starting to work on the template.
% \section{How to Use this Template}
% The template details the sections that can be used in a manuscript. 
% Note that the order and names of article sections may differ
% from the requirements of the journal 
% (e.g., the positioning of the Materials and Methods section). 
% Please check the instructions for authors page of the journal 
% to verify the correct order and names. 
% For any questions, please contact the editorial office of the journal or
% support@mdpi.com. For LaTeX related questions please contact latex@mdpi.com.

Suggested 6750 words.

Install the wordcount package from \url{https://github.com/benmarwick/wordcountaddin} to count words.

Terminology for this paper:
%
\begin{enumerate}

  \item Light is the visible portion of the electromagnetic spectrum.
  
  \item ``spectrum'' means a range of wavelengths.
  
  \item ``spectra'' are several ranges of wavelengths.

  \item Light is a form of useful energy. Illumination is an energy service.
  
  \item Lamps are devices that convert electricity into light.
  
  \item To avoid ambiguity, we should not use ``lights'' to mean ``lamps.''

  \item Always be specific about energy and exergy.  
        Any time you use the words energy or exergy, be sure you mean it.  
        If you mean either, say ``energy or exergy.''

  \item Never use the word ``useful'' unless you mean the useful stage of the energy conversion chain.
  
  \item Let's be very clear about power and energy.  Use overdots ($\dot{X}$) to indicate powers (rates of energy).
  
  \item Review the nomenclature tables at the end of the paper.  
        If you use a new variable name, be sure you can't use a letter that already exists in the nomenclature tables.
        If you must use a new variable letter, add it to the table the first time you use it.
        
  \item Only single letters for main variable names.  
        Use subscripts to provide additional meaning.  
        Use decorations to indicate rates.
        
  \item The exergy-to-energy ratio ($\phi$) is \emph{not} second law efficiency ($\eta_X$)
        The energy-to-exergy ratio ($\phi$) applies at every statepoint.  
        $\eta_E$ and $\eta_X$ apply across energy conversion devices.
        
  \item Power is energy per time. watts are power.
  
  \item Spectral radiant power and radiant power refer to the electromagnetic radiation emitted 
        by a lamp as measured directly in Watts. Spectral luminous power and luminous power \emph{only} refer
        to the electromagnetic radiation emitted by a lamp as measured in lumens (by applying the photopic luminosity function,
        and multiplying by a factor of 683 lm/W)
  
  \item Flux is quantity per unit area per unit time. W/m$^2$ is a flux.
        
  \item Do not confuse power and flux.  Do not write ``radiant power/flux,''
        seemingly indicating that power and flux
        are synonyms.  Power and flux are not synonyms.

\end{enumerate}
%

Style for this paper:
%
\begin{enumerate}

  \item Do not use ``this,'' ``that'', or ``it'' as the subject of a sentence. (MKH pet peeve!)
        Sentences that have those words as subjects are 
        almost never clear to the reader
        yet almost always clear to the writer.
        Why? The antecedent is almost always ambiguous.

  \item Spell out ``Figure~X,'' ``Equation~Y,'' and ``Table~Z.''  Capitalize all.
  
  \item Use SI units for everything.
  
  \item Every number that deserves a unit must have a unit.  Do not write ``683'' without units, for example. 
  
  \item Use the Oxford comma:  ``This, that, and the other;'' not ``This, that and the other.''
  
  \item Write comments to other authors in the text with ``**** comment --- MKH ****''.
  
  \item Let's use a space between numbers and percent signs. Best to use a non-breaking space (see below).
  
  \item The word data is plural, not singular.  The word datum is singular.

\end{enumerate}
%

\LaTeX{} hints:
%
\begin{enumerate}
	
  \item Use short lines with return characters after every clause.  
  
  \item Comment lines after the equation environment to continue a sentence or paragraph.
  
  \item Check comments in \texttt{LightingPaper2020.bib} file for hints about bibliography generation.
  
  \item Use ``\textasciitilde'' character for non-breaking space. 
        ``\textasciitilde'' is especially useful between numbers and their units.
        E.g., 683\textasciitilde{}lm/W.
        
  \item Quotation marks: Opening quotes with two back-tics: ``.
        Closing quotes with two apostrophes: ''.
        Do not use the quotation mark key on the keyboard.
    
\end{enumerate}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction (PB, 500 words)}
\label{sec:introduction}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% The introduction should briefly place the study in a broad context and
% highlight why it is important.
% It should define the purpose of the work and its significance. 
% The current state of the research field should be reviewed carefully and
% key publications cited.
% Please highlight controversial and diverging hypotheses when necessary. 
% Finally, briefly mention the main aim of the work and highlight the principal conclusions. 
% As far as possible, please keep the introduction comprehensible 
% to scientists outside your particular field of research. 
% Citing a journal paper or book~\cite{Delgado-Bonal:2017aa}. 


% PB: Make the paper broader than SEA.
% Also discuss other fields: highly-technical lighting papers, Emergy, etc
% All have different ways of dealing with the \enaex{} of light.
% PB: Need to discuss societal exergy analysis.
% PB: Need to discuss the energy conversion chain and P, F, U, S stages.
% (Needed for Section~\ref{sec:framework} later.)
% Point out that human perception and satisfaction of human needs is accomplished post-useful stage.
% PB: Discuss lighting as one aspect of ECC analysis.
% Probably more important in earlier years.
% But studies are pushing back to 1800s,
% so getting this right is important.
% PB: Discuss Fouquet~\cite{Fouquet:2006}, who looked at energy, but not exergy.
% Point out that we are discussing light for illumination, not for horticultural and other purposes.



% \textbf{(Broad context and the problem)}

%++++++++++++++++++++++++++++++
\subsection{Broad context and the problem}
\label{sec:broad_context}
%++++++++++++++++++++++++++++++

Artificial light provides an indispensable energy service (illumination), 
enabling activities at times when natural light levels are insufficient.
Artificial illumination is so valuable that around 20~\% of global grid-connected electricity 
is consumed for the purpose of making light~\cite{waide2006}.
With the modern breakthrough technology of light emitting diode (LED) lamps,
which now comprise 40~\% of residential lamp sales~\cite{IEA2019},
applications have spread beyond illumination to many other fields
including human physiology and photosynthesis for horticulture~\cite{Pattison2018LEDefficacy}.
The use and analysis of the energy and exergy efficiency of lighting is applied to a range of fields,
including energy economics~\cite{Nordhaus1996},
societal exergy analysis~\cite{Ayres2005},
energy history~\cite{Fouquet:2006},
and forecasting energy efficiency improvements~\cite{IEA2019}.
However, a key problem arises for the energy analyst:
there are differing concepts and definitions of lighting efficiency.
These differences matter on two counts.
First, with the rise of LED lamps,
the proximity to the efficiency limits of lighting appears within reach – but what is the limit?
Second, given the expanding role that artificial lighting plays globally,
understanding precisely 
its potential contribution---via increasing efficiency---to reducing energy use
to meet carbon dioxide emission targets is crucially important.
The aim of this paper is therefore to bring clarity to the analyst 
on the definitions of the energy and exergy conversion efficiency 
of artificial light for illumination.
Our application is societal exergy analysis, and 
we exclude non-illumination purposes, such as horticulture and heating.


%++++++++++++++++++++++++++++++
\subsection{Lighting fundamentals}
\label{sec:lighting_fundamentals}
%++++++++++++++++++++++++++++++

At the outset, we define two fundamental aspects of lighting,
with more detail coming in **** Sections X and Y ***.
The first fundamental aspect of lighting is a clear definition of what we mean by \emph{light}.
Light is useful energy in the form of 
electromagnetic (EM) radiation. 
Light energy is quantified in terms of 
energy~($E$),
wavelength~($\lambda$), and
frequency~($\nu$), 
all related by Planck's equation:
%
\begin{equation}
  E = h \nu = \frac{hc}{\lambda} \; ,
\end{equation}
%
where $c$ is the speed of light (in m/s).
**** PB: Add example units in preceding senetence. Is E in J or J/s? ---MKH ****
EM radiation within the range \humaneyesensitivity{} is considered ``light''~\cite{campbell2017}, because
the human retina responds only within these wavelengths,
as shown in Figure~\ref{fig:Vis_Graph}.

<<Load_Data, cache=use_cache, cache.extra.1=tools::md5sum('Data/master_lighting_data.xlsx'), cache.extra.2=tools::md5sum('Data/AllData.R')>>=
# Creates the weighted_responses_df data frame.
source(file = file.path("Data", "AllData.R"))
# Trim down to the weighting functions and lamps we want
wf_list <- c(Unweighted = "wf_nw", Visible = "wf_v",
             Photopic = "wf_p2", Universal = "wf_u")
lamp_list <- c(INC = "lamp_inc_globe_a19_40w", HPS = "lamp_hps_phil", 
               CFL = "lamp_cfl_es_tw", LED = "lamp_led_phil_a19")

# Create versions of wf_list and lamp_list suitable for use in the recode function
# by swapping names and values.
wf_list_for_recode <- names(wf_list) %>%
  magrittr::set_names(wf_list)
lamp_list_for_recode <- names(lamp_list) %>%
  magrittr::set_names(lamp_list)

response_data <- weighted_responses_df %>% 
  dplyr::filter(
    wf_name %in% wf_list, 
    lamp_name %in% lamp_list, 
  ) %>% 
  dplyr::mutate(
    wf_name = factor(wf_name, levels = wf_list), 
    wf_name = dplyr::recode_factor(wf_name, !!!wf_list_for_recode),
    lamp_name = factor(lamp_name, levels = lamp_list),
    lamp_name = dplyr::recode_factor(lamp_name, !!!lamp_list_for_recode)
  )
@


<<Vis_Graph, cache=use_cache, fig.align="center", fig.width = 5, fig.height = 3, fig.cap="The visible spectrum of light~\\cite{schubert2006}.">>=
response_data %>% 
  dplyr::filter(wf_name == "Photopic") %>% 
  dplyr::select("Wavelength [nm]", "normalized_response", "wf_name") %>% 
  dplyr::mutate(
    # Get nice tails at 0.
    normalized_response = tidyr::replace_na(normalized_response, 0)
  ) %>% 
  ggplot2::ggplot(mapping = aes(x = `Wavelength [nm]`)) +
  ggspectra::stat_color(mapping = aes(x = `Wavelength [nm]`, y = normalized_response), 
                        geom = "bar",
                        chroma.type = chroma_type,
                        size = 0) +   # Eliminates borders
  scale_fill_identity() +
  scale_color_identity() +
  geom_line(mapping = aes(y = normalized_response), color = "darkgray") +
  geom_vline(xintercept = 555, size = 0.2, color = "darkgray") +
  xlab(expression(lambda*" [nm]")) +
  ylab("Normalized sensitivity [-]") +
  scale_x_continuous(limits = c(250, 900), breaks = c(250, 380, 555, 750, 900)) + 
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
  MKHthemes::xy_theme() + 
  theme(axis.text.x = element_text(size = rel(0.8), angle = 90), 
        axis.text.y = element_text(size = rel(0.8)))
@

The second fundamental aspect of light is that 
modern lighting is provided by energy conversion through three stages
of the energy conversion chain:
primary energy (e.g., coal), which is then converted to
final energy (i.e., electricity, measured in watts), and last to
useful energy output (i.e., the provision of visible light energy, measured in lumens).
The efficiency of energy conversion~($\eta$) from the final stage (electricity) 
to the useful stage (light) is the focus of this paper.
We note that both human perception and satisfaction of human needs
are an energy service (illumination),
which occurs after the useful stage.


%++++++++++++++++++++++++++++++
\subsection{Diverging approaches to lighting efficiency}
\label{sec:divergent_approaches}
%++++++++++++++++++++++++++++++

**** Section~\ref{sec:divergent_approaches} feels a bit like Section~\ref{sec:further_challenges}.
We need to synchronize the two sections.
Furthermore, any issues raised here should be addressed clearly below. 
Sorting out this issue is mine.
For now, PB should do the edits that I suggest.---MKH ****

From this point, however, we stumble into sources of confusion surrounding 
the energy conversion efficiency ($\eta$) of lamps.
A conventional way to quantify conversion efficiency
is luminous efficacy (in lumens/watt, or lm/W),
which is luminous power (light output, in lm)
per electrical energy input (in W).
The first source of confusion is that some practitioners
equate luminous efficacy with luminous (or light) efficiency.
For example, \citet{Nordhaus1996} provides estimates of historical lighting efficiencies
from the earliest time of open wood fires (0.002~lm/W),
through to candles (0.1~lm/W),
tungsten filament lamps (10~lm/W) and
compact fluorescent light bulbs (68~lm/W).
\citet[p.~265]{Tsao2010appetitelight} are very clear,
but wrong, when they state
``[l]uminous efficacy represents the efficiency with which energy is used to produce visible light.''
Luminous efficacy is commonly taken to be a proxy
for energy efficiency, but they are not equivalent.
**** Why?  Need to explain.
Can we be more specific?  Luminous efficacy is a final-energy-to-service 
efficiency, not an energy efficiency? 
Or something similar? ---MKH ****
**** I propose the following " ...but they are not equivalent, as the lumen is not a measure of the total visible light emitted by a lamp, as further discussed in section 2.1.3. ---ZM ****

Others (***REF***) more correctly define efficiency of light provision on a thermodynamic basis, namely the \emph{luminous efficiency},as follows:
%
\begin{equation} \label{eq:eta_eqn}
  \eta = \frac{\text{actual lamp efficacy [lm/W]}}{\text{theoretical maximum efficacy limit [lm/W]}} \; .
\end{equation}

**** It will not be clear to the reader why Equation~\ref{eq:eta_eqn} is more correct
than luminous efficacy. We need to spell it out. ---MKH ****

**** I'm not sure whether this equation is inherently more correct. I think we should change this to "Others calculate the efficiency of a lamp, positing it to be the final to useful exergy efficiency, by taking the quotient of a lamps luminous efficacy and the maximum luminous efficacy as follows. This approach is discussed further in section 2.2.1 ---ZM ****


However, Equation~\ref{eq:eta_eqn} takes us straight into two further sources of confusion:
the numerator and the denominator.
The confusion of the numerator, 
as set out by \citet{Paoli2020},
is how to quantify actual lamp efficacy. 
Should one use quantify lamp output by 
omni-directional or 
directional (aimed at the point of illumination) lumens?
Should one measure electricity at the wall plug or at the lamp itself?

The other, and perhaps more controversial, source of confusion
is the denominator: 
\emph{what is the theoretical maximum efficacy limit} (in lm/W)?
Within the literature, three common values are adopted:
220~lm/W \cite[Table~5.6.9]{Ayres2003, USDepartmentofEnergyDoE2011},
400~lm/W \cite{Ayres2005, Tsao2010solidstate, Summers1971, Guevara2016}, and
683~lm/W \cite{Kondo2009, Serrenho2014}, based on the maximum efficacy of a ???, white light, and light at 555nm respectively.

Even within technical lighting papers,
there is divergence over the theoretical maximum efficacy limit of lamps,
due to differing decisions of what ``luminosity function'' to adopt,
as the eye is differentially sensitive wavelengths within the visible range (\humaneyesensitivity{}).
Such differences are still very recent
\cite{Delgado-Bonal:2017aa, Pattison2018LEDphotons, Rea2018, Royer2016}.
**** Preceding sentence probably doesn't say what you want it to say.
Do you mean, ``such differences remain contentious?'' ---MKH ***
With the introduction of high-efficiency LED lamps, which
are tunable to maximize output at different visible wavelengths,
the issue of differential sensitivity of the human eye has urgency,
as shown in Figure~\ref{fig:LuminousEfficacy_Graph}.
**** I don't think that Figure~\ref{fig:LuminousEfficacy_Graph}
demonstrates the issue of differential eye sensitivity.
I think Figure~\ref{fig:Vis_Graph} shows differential eye sensitivity. ---MKH ****


<<Load_LEData, cache=use_cache, cache.extra.1=tools::md5sum('Data/Lighting_Efficacy_Data.xlsx'), cache.extra.2=tools::md5sum('Data/lighting_efficacy.R')>>=
# Creates the le_df data frame.
source(file = file.path("Data", "lighting_efficacy.R"))
@

<<LuminousEfficacy_Graph, cache=use_cache, fig.align="center", fig.width = 5, fig.height = 4, fig.cap = "The luminous efficacy of selected lamp technologies from 1880 to 2020. For HPS lamps, data was limited to lamps of less than 100~W as a lamp's luminous efficacy tends to increase in line with its electricity consumption, therefore skewing the results for a particular year, depending on the wattage of the lamp reported. Data were obtained from three sources: the Museum of Electric Lamp Technology (LampTech)~\\cite{hooker_2020}, the ENERGYSTAR database of certified light bulbs~\\cite{energystar_2020}, and the lighting market characterization reports commissioned by the US Department of Energy (DOE)~\\cite{DOE2002, DOE2012, DOE2017}." >>=
le_df$Selected <- ifelse(le_df$Type == "LSPDD", "Selected lamps", "Other")

le_df_filtered <- le_df %>% 
  dplyr::filter(!is.na(Selected))

textdf <- le_df_filtered[le_df_filtered$Type == "LSPDD", ]

ggplot2::ggplot(le_df_filtered, mapping = aes(x = Year)) +
  geom_point(mapping = aes(y = `Luminous Efficacy [lm/W]`, 
                           colour = Technology, 
                           shape = Selected)) +
  ggrepel::geom_text_repel(data = textdf, 
                           mapping = aes(x = Year, y = `Luminous Efficacy [lm/W]`, label = Device), 
                           size = 3, # Size of text label
                           segment.size = 0.2, # Width of line
                           arrow = arrow(length = unit(0.01, "npc")),
                           box.padding = unit(0.2, "lines"),
                           point.padding = unit(0.3, "lines"),
                           nudge_x = -75,
                           nudge_y = 0, 
                           colour = "gray50") + 
  
  MKHthemes::xy_theme() +
  theme(legend.position = "bottom", legend.box="vertical",
        legend.text = element_text(size = 8),
        axis.title.x=element_blank(), 
        legend.title=element_blank()) + 
  guides(col = guide_legend(nrow = 2)) +
  scale_colour_manual(values = c("darkgreen", "lightblue", "darkred", "darkorange")) +
  scale_x_continuous(breaks = seq(from = 1880, to = 2020, by = 20)) + 
  guides(shape = FALSE)
@

A final source of confusion is the differences between 
first law (energy) and second law (exergy) efficiencies.
Few authors make the distinction, and
most inadvertently adopt a second law efficiency
(Equation~\ref{eq:eta_eqn})
**** We haven't made the argument that Equation~\ref{eq:eta_eqn} is an exergetic efficiency. ---MKH ****.
\citet{Schaeffer1992} and 
\citet{Nakicenovic1996} 
provide rare exceptions
when they define both final-to-useful energy efficiency of lamps
(ranging from incandescent, 5~\%, to fluorescent, 20~\%)
and energy-to-exergy useful stage efficiency of 90--93\%.
**** This is crossing the streams. I DO NOT want to say that the exergy-to-energy ratio is an efficiency 
of any kind. 
The exergy-to-energy ratio is $\phi$.  Full stop. 
It is not an efficiency.
Efficiencies are ONLY measured ACROSS an energy conversion device.
Efficiencies are NOT measured at an energy conversion stage (useful).
Can you try to restate the previous sentence, 
possibly by simplifying it?
Or delete entirely? ---MKH ****

**** Should we end here with the question for this paper? ---MKH ****


%++++++++++++++++++++++++++++++
\subsection{Paper structure}
\label{sec:paper_structure}
%++++++++++++++++++++++++++++++

The article proceeds as follows.
In Section~\ref{sec:methods}, we set out the energy and exergy fundamentals of light.
In Section~\ref{sec:results}, we show results for example weighting functions and lamps before
presenting a discussion in Section~\ref{sec:discussion}. 
Section~\ref{sec:conclusions} concludes.
Our key finding is ******.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Methods (2250 words)}
\label{sec:methods}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 

% Materials and Methods should be described with sufficient details 
% to allow others to replicate and build on published results. 
% Please note that publication of your manuscript implicates 
% that you must make all materials, data, computer code, and protocols
% associated with the publication available to readers. 
% Please disclose at the submission stage any restrictions 
% on the availability of materials or information. 
% New methods and protocols should be described 
% in detail while well-established methods 
% can be briefly described and appropriately cited.
% 
% Research manuscripts reporting large datasets that are deposited
% in a publicly available database should specify 
% where the data have been deposited and provide the relevant accession numbers. 
% If the accession numbers have not yet been obtained at the time of submission, 
% please state that they will be provided during review. 
% They must be provided prior to publication.
% 
% Interventionary studies involving animals or humans, and other studies
% require ethical approval must list the authority 
% that provided approval and the corresponding ethical approval code. 



%++++++++++++++++++++++++++++++
\subsection{Exergy theory (MKH, 1000 words)}
\label{sec:framework}
%++++++++++++++++++++++++++++++

Energy and exergy are two methods to quantify the physical property that,
when transferred to an object,
changes its temperature or performs work on it.
(For this discussion, we can't call the ``physical property'' energy, exergy, work, or heat,
because these concepts need to remain separated. 
So, we use the generic term ``physical property.'')
We discuss energy and exergy quantifications of the physical property in the sections below, 
beginning with heat and work, 
the concepts for which \enaex{} originated.
Thereafter, we develop a framework for the \enaex{} of light
in a parallel manner to the \enaex{} of heat and work.


%------------------------------
\subsubsection{\Enaex{} ($\dot{E}$ and $\dot{X}$) of heat and work} 
\label{sec:energy_and_exergy_of_heat_and_work}
%------------------------------

Energy quantifies the physical property by its heat content.
Thus, heat (the ability to influence temperature) is pure energy.
Thanks to Thompson's cannon experiment~\cite{Thompson:1798aa}, 
we know that work can be converted, without loss, into heat.

Figure~\ref{fig:heat_engine} shows a heat engine that converts 
heat at $1$ to 
work at $3$
with a waste heat byproduct at $2$. 
All streams can be counted as energy ($\dot{E}$), such that 
%
\begin{equation} \label{eq:all_streams_energy}
  \dot{E}_1 = \dot{Q}_1, \; \dot{E}_2 = \dot{Q}_2, \; \text{and} \; \dot{E}_3 = \dot{W}_3 \; .
\end{equation}


\begin{figure}
\centering
\begin{tikzpicture}
  % Set up the nodes of the main path
  % Machine node
  \node(machine)[draw, rounded corners, fill=yellow!25!white, 
                 minimum width = 2.5 cm, minimum height = 1.5 cm] at (0cm, 0cm) {\strut Heat engine};
  % Number nodes
  \node[left=3cm of machine] (1)[circle, fill=red!25!white] {\strut 1};
  \node[above right = -0.7cm and 3cm of machine] (2)[circle, fill=red!25!white] {\strut 2};
  \node[below right = -0.7cm and 3cm of machine] (3)[circle, fill=red!25!white] {\strut 3};
  % Arrows
  \draw[arrows=-triangle 45] (1) -- node [above] {$T_1 , \; \dot{Q}_1 \; \text{(heat)}$} (machine);
  \draw[arrows=-triangle 45] (2 -| machine.east) -- node [above] {$\dot{Q}_2 \; \text{(heat)}, \; T_2$} (2.west);
  \draw[arrows=-triangle 45] (3 -| machine.east) -- node [below] {$\dot{W}_3 \; \text{(work)}$} (3.west);
\end{tikzpicture}
\caption{A heat engine that produces work and heat.}
\label{fig:heat_engine}
\end{figure}

Energy efficiency is defined as $\eta_E \equiv \frac{\text{energy out}}{\text{energy in}}$.
For the example of Figure~\ref{fig:heat_engine}, 
%
\begin{equation} \label{eq:energy_efficiency}
  \eta_E = \frac{\dot{E}_2 + \dot{E}_3}{\dot{E}_1} = \frac{\dot{Q}_2 + \dot{W}_3}{\dot{Q}_1} = 1 \; ,
\end{equation}
%
because the first law of thermodynamics 
states that energy is conserved ($\dot{Q}_1 = \dot{Q}_2 + \dot{W}_3$).

That said, typically only one of the products in Figure~\ref{fig:heat_engine} 
is deemed valuable: the work produced by the heat engine ($\dot{W}_3$).
Thus, the \emph{valuable} energy efficiency ($\eta_{E,v}$) is 
%
\begin{equation} \label{eq:valuable_energy_efficiency}
  \eta_{E,v} = \frac{\dot{E}_3}{\dot{E}_1} = \frac{\dot{W}_3}{\dot{Q}_1} < 1 \; .
\end{equation}

Heat (the ability to influence temperature) is 
only one outcome of transferring the physical quantity
from one object to another.
Heat is certainly valuable to humans, but so is another quantity: 
work, the ability to exert a force on another object.
Exergy quantifies the physical property by its work potential
and provides the answer to the question
``what is the maximum work we could obtain from a stream of this physical property?''
Thus, work is pure exergy.

The Kelvin-Planck statement of the second law of thermodynamics 
states that heat cannot be converted to work without loss. 
To find the maximum possible work that can be created from heat 
(and, therefore, the exergy of heat), 
we consider the Carnot heat engine which operates at the maximum possible valuable energy efficiency~($\eta_C$), 
%
\begin{equation} \label{eq:eta_C}
  \eta_C = 1 - \frac{T_0}{T_{sys}} \; ,
\end{equation}
%
where $T_0$ is the ambient temperature and $T_{sys}$ is a heat temperature 
($T_1$ or $T_2$ in Figure~\ref{fig:heat_engine}).
The exergy of each stream in Figure~\ref{fig:heat_engine} is then
%
\begin{align}
  \dot{X}_1 &= \phi_1 \dot{Q}_1 = \left(1 - \frac{T_0}{T_1} \right) \dot{Q}_1, \\
  \dot{X}_2 &= \phi_2 \dot{Q}_2 = \left(1 - \frac{T_0}{T_2} \right) \dot{Q}_2, \; \text{and} \\
  \dot{X}_3 &= \cancelto{1}{\phi_3} \dot{W}_3 = \dot{W}_3 \; .
\end{align}
%
In this context, the Carnot efficiency~($\eta_C$) becomes the exergy-to-energy ratio
for heat streams ($\phi_Q = \eta_C$).
The exergy-to-energy ratio for work is $\phi_3 = \phi_W = 1$, 
because work is pure exergy.

Exergy efficiency is defined as $\eta_X \equiv \frac{\text{exergy out}}{\text{exergy in}}$.
For the heat engine in Figure~\ref{fig:heat_engine}, 
%
\begin{equation} \label{eq:exergy_efficiency}
  \eta_X = \frac{\dot{X}_2 + \dot{X}_3}{\dot{X}_1} = \frac{\dot{Q}_2 \left( 1 - \frac{T_0}{T_2} \right)  + \dot{W}_3}
                {\dot{Q}_1 \left( 1 - \frac{T_0}{T_1} \right) } < 1 \; .
\end{equation}
%
Exergy efficiency ($\eta_X$) is less than 1, because the second law of thermodynamics 
states that exergy is always destroyed ($\dot{X}_1 > \dot{X}_2 + \dot{X}_3$, or 
$\dot{X}_D = \dot{X}_1 - (\dot{X}_2 + \dot{X}_3)$).

Assuming, again, that work is valuable gives
%
\begin{equation} \label{eq:valuable_exergy_efficiency}
  \eta_{X,v} = \frac{\dot{W}_3}{\dot{Q}_1 \left( 1 - \frac{T_0}{T_1} \right) } < \eta_X < 1\; .
\end{equation}

Note that both $\eta_{E,v}$ and $\eta_{X,v}$ 
are independent of human presence.
The work created by the heat engine~($\dot{W}_3$) could be 
a spinning driveshaft on an automobile carrying four passengers down the freeway or
the same spinning driveshaft on a dynamometer in an unoccupied laboratory.
Both
%
\begin{enumerate*}[label={(\alph*)}]
	
  \item the \enaex{} of the work and heat at statepoints 2 and 3 and
  
  \item the \enaex{} efficiencies of the heat engine ($\eta_{E,v}$ and $\eta_{X,v}$)
    
\end{enumerate*}
%
would be the same, regardless.
In other words, both 
%
\begin{enumerate*}[label={(\alph*)}]
	
  \item the \enaex{} of work and heat and
  
  \item the efficiencies of the heat engine
    
\end{enumerate*}
%
are independent of human presence and the energy service provided by the heat engine.

We now turn to the production of light instead of work.


%------------------------------
\subsubsection{\Enaex{} ($\dot{E}$ and $\dot{X}$) of light} 
\label{sec:energy_and_exergy_of_light}
%------------------------------

Figure~\ref{fig:lamp} replaces the heat engine with a lamp 
that produces EM radiation~($\Phi_{EM,3}$) instead of work~($\dot{W}_3$).
Like Figure~\ref{fig:heat_engine},
electricity powers the lamp at 1, and 
waste heat (conduction and convection only) is produced at 2.

\begin{figure}
\centering
% \largemachinefigure{Lamp}
%                    {$\dot{W}_1 \; \text{(elec)}$}
%                    {$\dot{Q}_2$ (heat)}
%                    {$\Phi_{EM,3}$ (EM)}
%                    {$\dot{L}_4$ (light)}
\begin{tikzpicture}
  % Set up the nodes of the main path
  % Machine node
  \node(machine)[draw, rounded corners, fill=yellow!25!white, 
                 minimum width = 2.5 cm, minimum height = 1.5 cm] at (0cm, 0cm) {\strut Lamp};
  % Number nodes
  \node[left=2cm of machine] (1)[circle, fill=red!25!white] {\strut 1};
  \node[above right = -0.7cm and 2cm of machine] (2)[circle, fill=red!25!white] {\strut 2};
  \node[below right = -0.7cm and 2cm of machine] (3)[circle, fill=red!25!white] {\strut 3};
  
  \node(wf)[draw, rounded corners, fill=yellow!25!white, 
            minimum width = 2.5 cm, minimum height = 1.5 cm,
            align = center, right = 1 cm of 3] {\strut Weighting\\function ($f_{\lambda}$)};
  
  \node[right = 1 cm of wf] (4)[circle, fill=red!25!white] {\strut 4};
  
  % Arrows
  \draw[arrows=-triangle 45] (1) -- node [above] {$\dot{W}_1 \; \text{(elec)}$} (machine);
  \draw[arrows=-triangle 45] (2 -| machine.east) -- node [above] {$\dot{Q}_2$ (heat)} (2.west);
  \draw[arrows=-triangle 45] (3 -| machine.east) -- node [below] {$\dot{E}_{EM,3}$} (3.west);
  \draw[arrows=-triangle 45] (wf -| 3.east) -- node [below] {} (wf.west);
  \draw[arrows=-triangle 45] (4 -| wf.east) -- node [below] {$\dot{E}_{L,4}$} (4.west);

\end{tikzpicture}
\caption{****
EA: Please adjust this figure to match the nomenclature that I proposed on 2020-07-18.---MKH
****
A lamp that produces heat and light with 
an energy efficiency $\eta_{E,v}$, and a weighting function $f_\lambda$ that converts electromagnetic radiation (EM) into light with an energy efficiency $\eta_{E \{f_\lambda\}}$. Note that $\eta_{E \{f_\lambda\}}$ is function of the spectral distribution of the radiant power $\Phi_{EM,3}$. The efficiency with which the system lamp and weighting function converts electricity energy into light energy is noted $\eta_{E \{lamp, f_\lambda\}}$. Note that the same rationale is valid when considering exergy efficiency.}
\label{fig:lamp}
\end{figure}

Both electricity and EM radiation can be converted to heat without loss, so they are pure energy.
Thus,
%
\begin{equation}
  \dot{E}_1 = \dot{W}_1, \; \dot{E}_2 = \dot{Q}_2, \; \text{and} \; \dot{E}_3 = \Phi_{EM,3} \; .
\end{equation}
%
The energy efficiency~($\eta_E$) for the lamp in Figure~\ref{fig:lamp} is 
%
\begin{equation}  
  \eta_E = \frac{\dot{E}_2 + \dot{E}_3}{\dot{E}_1} = \frac{\dot{Q}_2 + \Phi_{EM,3}}{\dot{W}_1} = 1 \; ,
\end{equation}
%
and the valuable energy efficiency~($\eta_{E,v}$) for the lamp in Figure~\ref{fig:lamp} 
(assuming that the EM radiation is the valuable output from the lamp) is
%
\begin{equation} \label{eq:eta_E_v}
  \eta_{E,v} = \frac{\dot{E}_3}{\dot{E}_1} = \frac{\Phi_{EM,3}}{\dot{W}_1} < 1 \; .
\end{equation}

This is also termed the \emph{wall plug efficiency}.
Because electricity can be converted to work without loss in a frictionless motor,
electricity is considered pure exergy, i.e., $\phi_{elect} = 1$.
Thus, the exergy of the first three streams in Figure~\ref{fig:lamp} is given by 
%
\begin{equation}
  \dot{X}_1 = \cancelto{1}{\phi_{elect}} \dot{W}_1 = \dot{W}_1, \; 
              \dot{X}_2 = \left( 1 - \frac{T_0}{T_2} \right) \dot{Q}_2, \; \text{and} \; 
              \dot{X}_3 = \phi_{\EM} \Phi_{EM,3} \; ,
\end{equation}
%
where the term $\phi_{EM}$ is the exergy-to-energy ratio for broad-spectrum EM radiation. 
(See Section~\ref{sec:phi_light} for details.)

The term $\Phi_{EM,3}$ is the radiant power of broad-spectrum EM radiation
emitted by the lamp in units of energy per unit time.
In general, the radiant power of a lamp is a spectral quantity,
meaning that it varies with wavelength.
Spectral radiant power~($\Phi_{EM,\lambda}$)
is the EM emissive power available at any wavelength
and is related to radiant power~($\Phi_{EM}$) in \citet{benenson2006handbook} by
%
\begin{equation} \label{eq:emissive_power}
  \Phi_{EM} = \int \Phi_{EM,\lambda} \mathrm{d}\lambda \; .
\end{equation}
%
Visually, $\Phi_{EM}$ is the area under the $\Phi_{EM,\lambda}$ vs.\ $\lambda$ curve.

The exergetic efficiency of EM radiation emitted by the lamp in Figure~\ref{fig:lamp} is given by
%
\begin{equation}
  \eta_X = \frac{\dot{X}_2 + \dot{X}_3}{\dot{X}_1} 
          = \frac{\left( 1 - \frac{T_0}{T_2} \right) \dot{Q}_2 + \phi_{EM} \Phi_{EM,3} }{\dot{W}_1} < 1 \; ,
\end{equation}
%
where $\phi_{EM}$ is the exergy-to-energy ratio of EM radiation.
In general, $\phi_{EM}$ is also a spectral quantity.
(See Section~\ref{sec:phi_light}.)
The valuable exergetic efficiency of the EM radiation emitted by the lamp in Figure~\ref{fig:lamp} is given by
%
\begin{equation} \label{eq:eta_X_v}
  \eta_{X,v} = \frac{\dot{X}_3}{\dot{X}_1} 
              = \frac{\phi_{EM} \Phi_{EM,3} }{\dot{W}_1} < \eta_X < 1 \; .
\end{equation}

Note that both $\eta_X$ and $\eta_{X,v}$ are independent of human presence;
the efficiencies ($\eta_X$ and $\eta_{X,v}$) would be the same 
whether the lamp is illuminating
an unoccupied room or a crowded bar, 
whether the illumination stimulates the rods and cones of a human eye or
excites band gap electrons in an amorphous silicon solar cell.


%------------------------------
\subsubsection{Human perception of EM radiation} 
\label{sec:human_perception_of_EM_radiation}
%------------------------------

We noted above that both
%
\begin{enumerate*}[label={(\alph*)}]

  \item \enaex{} of light and

  \item \enaex{} efficiency of lamps

\end{enumerate*}
%
are independent of human presence.
But what about human \emph{perception}?

Human beings perceive heat by temperature and light by wavelength.
Human skin can perceive the thermal radiation portion of the broader electromagnetic spectrum,
approximately 100 nm < $\lambda$ < 10,000 nm. 
Furthermore, human skin is differentially sensitive to EM spectrum wavelength.  
Indeed, thermoreceptors in the dermis of skin are important sensors for regulation of body temperature.
****
Need a reference here.---MKH
****
Similarly, human eyes perceive only a (narrower) portion of the EM radiation emitted by lamps
(approximately \humaneyesensitivity).
To quantify light energy (and exergy), we must move from broad-spectrum emitted EM energy~($\Phi$)
to light~($\dot{L}$). 
But how?

Knowing that visual perception of light is a function of wavelength
leads to modifying Equation~\ref{eq:emissive_power}
to include a spectral weighting function~($f_\lambda$) such that
%
\begin{equation} \label{eq:weighted_emissive_power}
  \dot{L} = \int \Phi_{L,\lambda} \mathrm{d}\lambda = \int f_\lambda \Phi_{EM,\lambda} \mathrm{d}\lambda \; ,
\end{equation}
%
with $0 \le f_\lambda \le 1$
and $\Phi_{L,\lambda} = f_\lambda \Phi_\lambda$.

In Equation~\ref{eq:weighted_emissive_power}, 
the spectral weighting function~($f_\lambda$) converts 
from EM radiation~($\Phi_{EM}$)
to light~($\dot{L}$), 
the valuable part of EM radiation for illumination.
In the context of Figure~\ref{fig:lamp}, 
%
\begin{equation} \label{eq:L_dot_4}
  \dot{L}_4 = \int f_\lambda \Phi_{EM,\lambda,3} \mathrm{d}\lambda \; .
\end{equation}


%------------------------------
\subsubsection{The exergy-to-energy ratio of EM radiation, $\phi_{\EM}$ (Zeke and Emmanuel, 500 words)}
\label{sec:phi_light}
%------------------------------

Recent advances in the thermodynamics of radiation community
enable converting the energy of EM radiation into the exergy of EM radiation.
The exergy-to-energy ratio of EM radiation
($\phi_{\EM}$, called the ``radiative exergy-energy coefficient'' in that community)
is given by Petela's Equation~\cite{petela1964exergy}:
%
\begin{equation} \label{eq:petelas_equation}
 \phi_{\EM} = 1 - \frac{4}{3}\frac{T_{0}}{T_{1}} + \frac{1}{3} \left(\frac{T_{0}}{T_{1}}\right)^4 \; .
\end{equation}

However, Petela's equation assumes a blackbody emitter and
a blackbody absorber 
at temperatures $T_1$ and $T_0$, respectively.
To determine $\phi_{\EM}$ for a non-blackbody lamp,
the spectral exergy-to-energy ratio ($\phi_{\EM,\lambda}$),
must be calculated.
An effective temperature of light photons~\cite{chen2008} ($T_\lambda$) 
provides the link between Petela's equation (Equation~\ref{eq:petelas_equation})
and the spectral exergy-to-energy ratio~($\phi_{\EM,\lambda}$).

Petela's equation has recently been verified through the development of an infinite-staged
Carnot engine model \cite{zhou2017exergy}, which describes the transfer of radiative energy.
In this model a photon possessing a characteristic frequency 
and photon effective temperature enters a medium which acts as an ideal absorber. 
The photon transfers an infinitesimal quantity of thermal radiation to the absorber, 
this thermal radiation then enters a Carnot heat engine and performs work. 
The absorber then emits another photon at a lower energy and frequency 
(and therefore lower photon effective temperature). 
This process is repeated until the frequency of the photon equals zero, 
and $T_0$ (the reference temperature) is equal to the photon effective temperature ($T_\lambda$)~\cite{Shan2019}.

We note that the use of the photon effective temperature approach has been criticized by 
\citet[p.~1810]{liu2009},
who argued that 
``to endue a single photon with macro-scale thermodynamic parameters
such as exergy and entropy'' is inappropriate.
We acknowledge this critique, 
but we also note that here $T_\lambda$ is ascribed to a stream of photons
traveling from a lamp to an eye.
Thus, for our purposes, $T_\lambda$ can be considered the statistical average effective temperature 
of the stream of photons.
****
Is this a good way to address the critique?---MKH
****
The product of wavelength and photon effective temperature is a constant~($c_3$ in \citet{chen2008}) such that
%
\begin{equation}
  \lambda T_{\lambda} = c_{3} = 5.33016 \times 10^{-3} \text{ m-K} \; ,
\end{equation}
%
or
%
\begin{equation} \label{eq:T_lambda}
  T_\lambda = \frac{5.33016 \times 10^{-3} \text{ m-K}}{\lambda} \; .
\end{equation}

We make the assumption that the mechanism
by which light is converted into electrical nerve signals
in the human eye
is radiative EM energy transfer
from a light source~(1) to an eye~(0).
We further assume that the human iris is a blackbody absorber 
(absorbing all wavelengths of radiation perfectly \cite{benenson2006handbook}), 
being a small aperture on a larger cavity.
(In this assumption, we follow \citet[p.~172]{Rossing2020} who state
``another good example of [a blackbody absorber] is the human eye;
the pupil looks black because most light entering it is trapped and absorbed.'')
Thus, we use Shan and Zhou's~\cite{Shan2019} spectral formulation of Petela's equation,
which replaces the temperature of the emitter ($T_1$) by photon effective temperature~($T_\lambda$):
%
\begin{equation} \label{eq:phi_EM_lambda_shan_zhou}
 \phi_{\EM,\lambda} = 1 - \frac{4}{3} \left( \frac{T_{0}}{T_{\lambda}} \right)
                        + \frac{1}{3} \left(\frac{T_{0}}{T_{\lambda}}\right)^4 \; .
\end{equation}
%
Further, Equation~\ref{eq:T_lambda} can be substituted into Equation~\ref{eq:phi_EM_lambda_shan_zhou}
(in the form $T_\lambda = c_3 / \lambda$),
and $T_0$ can be taken as 310~K, the temperature of the human body.
The result is an equation for $\phi_{L,\lambda}$, the specular exergy-to-energy ratio of light:
%
\begin{equation} \label{eq:phi_L_lambda_shan_zhou}
 \phi_{L,\lambda} = 1 
                    - \frac{4}{3} \left( \frac{310 \text{ K}}{c_3} \right) \lambda 
                    + \frac{1}{3} \left( \frac{310 \text{ K}}{c_3} \right)^4 \lambda^4 \; .
\end{equation}

We assume no losses in radiative transmission
between the lamp and the iris.
I.e., no radiation scattering occurs through air, 
an assumption that holds for short distances typically 
observed in lighting applications (<~10~m).
(See \citet{Shan2019} for a method to estimate transmission losses
over longer distances.)

The exergy of light emitted by a non-blackbody lamp~($\dot{X}_L$)
is found by integrating the product of
the spectral radiant power~($\Phi_{EM,\lambda}$),
a spectral weighting function~($f_\lambda$), and
the spectral exergy-to-energy ratio~($\phi_\lambda$)
with respect to wavelength.
%
\begin{equation} \label{eq:X_dot_L}
  \dot{X}_L = \int \phi_{L,\lambda} \, f_\lambda \, \Phi_{EM,\lambda} \mathrm{d}\lambda
\end{equation}

The quotient of $\dot{X}_{L}$ and $\dot{L}$ gives the overall exergy-energy ratio of light~($\phi_{L}$), 
which is specific to each combination of
lamp and weighting function ($f_\lambda \Phi_{EM,\lambda}$).

\begin{equation} \label{eq:phi_L}
  \phi_{L} = \frac{\dot{X}_L}{\dot{L}} 
           = \frac {\int \phi_{L,\lambda} f_\lambda \Phi_{EM,\lambda} \mathrm{d}\lambda}
                       {\int f_\lambda \Phi_{EM,\lambda} \mathrm{d}\lambda}
\end{equation}

Table~\ref{tab:EX_summary} summarizes the key equations in 
Sections~\ref{sec:framework}--\ref{sec:phi_light}.

\input{pieces/EX_summary.tex}


%------------------------------
\subsubsection{Light efficiency of a lamp} 
\label{sec:light_efficiency}
%------------------------------

If the valuable product of a lamp is considered to be its light~($\dot{L}$)
as opposed to its broadband EM radiation~($\Phi_{EM}$),
Equations~\ref{eq:eta_E_v} and~\ref{eq:eta_X_v} require modification.
In the context of Figure~\ref{fig:lamp}, the valuable energy efficiency of light becomes
%
\begin{equation} \label{eq:eta_E_v_light}
  \eta_{E,v} = \frac{\dot{E}_4}{\dot{E}_1} 
             = \frac{\dot{L}_4}{\dot{W}_1} 
             = \frac{\int f_\lambda \Phi_{EM,\lambda,3} \mathrm{d}\lambda}{\dot{W}_1} \; ,
\end{equation}
%
and the valuable exergetic efficiency of light becomes
%
\begin{equation} \label{eq:eta_X_v_light}
  \eta_{X,v} = \frac{\dot{X}_4}{\dot{X}_1} 
              = \frac{\int \phi_{L,\lambda} f_\lambda \Phi_{EM,\lambda,3} \mathrm{d}\lambda}{\dot{W}_1} \; .
\end{equation}


%++++++++++++++++++++++++++++++
\subsection{Examples and data}
\label{sec:examples_and_data}
%++++++++++++++++++++++++++++++

%------------------------------
\subsubsection{Weighting functions}
\label{sec:weighting_functions}
%------------------------------

Spectral weighting functions ($f_\lambda$) convert radiant power to light.
(See Section~\ref{sec:human_perception_of_EM_radiation}.)
We selected four spectral weighting functions relevant to illumination
to enable example calculations later (Section~\ref{sec:results}).

The first option is degenerate: 
the analyst could decide to ignore the nuances of human visual perception altogether,
implicitly assuming that all EM radiation emitted from a lamp is valuable, 
whether or not it is within the visible portion of the EM spectrum.
For the first option, the degenerate (unweighted, uw) weighting function ($f_{\lambda,uw}$) is
%
\begin{equation} \label{eq:f1}
  f_{\lambda,uw} = 1 \; .
\end{equation}

Second, the analyst could 
deem a lamp's EM radiation to be useful if and only if it \emph{could}
stimulate photoreceptive cells in the human eye,
regardless of the spectral sensitivity of those cells.
In the second option, the analyst excludes wavelengths outside the range of perception by the human eye
when determining the \enoex{} of light.
For the second option (visible, vis),
%
\begin{equation} \label{eq:f2}
f_{\lambda,vis} =
  \begin{cases}
    0 \; , & \text{for } \lambda < 380 \text{ nm} \\
    1 \; , & \text{for } 380 \text{ nm} \le \lambda \le 750 \text{ nm} \\
    0 \; , & \text{for } 750 \text{ nm} < \lambda \\
  \end{cases} \; .
\end{equation}

But the human eye is spectrally sensitive to EM radiation, 
with peak sensitivity at 555~nm (green)
and lesser sensitivities at both longer and shorter wavelengths.
A third option involves weighting a lamp's emitted EM radiation 
by the photopic sensitivity of the human eye.
The photopic luminosity~(pl) function~($V_\lambda$) describes this sensitivity, 
as shown in Figure~\ref{fig:Vis_Graph}.
The photopic luminosity function was
defined by the Commission Internationale de l' Éclairage (CIE) and 
represents the sensitivity of M and L cones
at daytime light levels \cite{CVRL2008}.
So for Option 3,
%
\begin{equation} \label{eq:f3}
  f_{\lambda,pl} = V_\lambda \; .
\end{equation}

Substituting Equation~\ref{eq:f3} into Equation~\ref{eq:weighted_emissive_power}
yields
%
\begin{equation}
  \dot{L}_{pl} = \int V_\lambda \Phi_{EM,\lambda} \mathrm{d}\lambda \; ,
\end{equation}
%
which provides the basis for calculating a lamp's output 
of visible light in the unit of lumens~(lm, $\Phi_{pl}$):
%
\begin{equation} \label{eq:lumen}
  \Phi_{pl} = (683 \text{ lm/W}) \; \dot{L}_{pl} \; ,
\end{equation}
%
where 683~lm/W is the EM power of a perfect light source emitting at $\lambda = 555 \text{ nm}$.
(See Figure~\ref{fig:Vis_Graph}.) 
(Note that because lumens are a re-scaling of watts, 
lumens are also a unit of radiant power.)

When the photopic luminosity function~($V_\lambda$) is used 
to calculate luminous power, 
the valuable energy efficiency of a lamp can be written in terms of luminous efficacy~($K$)
by modifying Equation~\ref{eq:eta_E_v_light} to be
%
\begin{equation} \label{eq:lum_effic_def}
  K = \frac{(683 \text{ lm/W}) \int V_\lambda \Phi_{EM,\lambda,3} \mathrm{d}\lambda}{\dot{W}_1}
\end{equation}
%
in the context of Figure~\ref{fig:lamp}, 
where $K$ is in lm/watt.

The photopic luminosity function~($V_\lambda$) is the industry standard for determining lumen output
of lamps, but it has been criticized for under-representing
the power of wavelengths different from 555~nm. 
In fact, the photopic luminosity function
neglects the differential sensitivity of the human eye's other light receptors,
namely the short-wave cones,
rods, and intrinsically photosensitive retinal ganglion cells (ipRGCs),
which are responsible for vision in low-light settings and
physiological functions such as the regulation of circadian rhythms.
Thus, the photopic luminosity function~($V_\lambda$) 
is said to have a long-wave bias.

A fourth option (universal, univ) weights a lamp's spectral radiant power~($\Phi_{EM,\lambda}$)
by the spectral sensitivity of all five light receptors in the human eye
(not just the M and L cones as does $V_\lambda$). 
The universal luminosity efficiency function ($U_\lambda$) \cite{Rea2018}
captures the actual, broader sensitivity of the human eye.
So, for option 4,
%
\begin{equation} \label{eq:f4}
  f_{\lambda,univ} = U_\lambda \; .
\end{equation}

Table~\ref{tab:wfs} summarizes the weighting functions discussed above.

\input{pieces/wfs.tex}


%------------------------------
\subsubsection{Lamps}
\label{sec:lamps}
%------------------------------

To demonstrate how the use of selection of spectral weighting function~($f_\lambda$)
alters the efficiency of a lamp, 
we need both weighting functions (Section~\ref{sec:weighting_functions}) and
example lamps.
Table~\ref{tab:lamps} summarizes details about lamps discussed throughout this paper.

We obtained spectral power distributions of the lamps in Table~\ref{tab:lamps} from the 
Light Spectral Power Distribution Database (LSPDD)~\cite{Roby, miguel2017, aube2013}. 

The data in the LSPDD are given 
in terms of \emph{relative intensity} ($\Phi_{rel,e\lambda}$) 
as opposed to \emph{absolute intensity}.
Because lamps in the LSPDD are not measured using an integration sphere,
the integral of the spectral power distribution may not match the radiant power of the lamp
supplied by the manufacturer.
To ensure that the integral of each lamp's spectral power distribution 
matches its reported radiant power, 
we applied the standard procedure of scaling the spectral power distribution 
by the ratio ($\mu$) of
the radiant power given by the manufacturer~($K \dot{W}_1$) and  
the integral of the spectral radiant power taken from the relative intensity data~($\Phi_{rel,EM}$).
%
\begin{equation} 
  \mu = \frac{K \dot{W}_1}{\Phi_{rel,EM}}   \; .
\end{equation}

We then applied the scaling factor~($\mu$) to to the spectral power distribution data for each lamp, 
yielding a scaled spectral power distribution data for each lamp 
that matches the manufacturer's reported radiant power ($\Phi_{EM,\lambda}$),
%
\begin{equation} 
  \Phi_{EM,\lambda}  = \mu \Phi_{rel,EM,\lambda}   \; .
\end{equation}

We selected one representative lamp for four common lamp technologies
(incandescent, INC;
high pressure sodium, HPS;
compact fluorescent, CFL; and
light emitting diode, LED), 
each with a unique spectral power distribution,
allowing for clear comparisons 
of the effects of spectral weighting functions~($f_\lambda$) and
the spectral exergy-to-energy ratio~($\phi_\lambda$).


<<lamps, cache=use_cache, results="asis", cache.extra.2=tools::md5sum('Data/results_lamp_info.R')>>=
source("Data/results_lamp_info.R")

print(xtable::xtable(results_lamp_info_fin, digits=0, 
                     caption = "Metadata for lamps, including 
                     year the spectral power distribution data was obtained, 
                     the luminous efficacy, 
                     electricity consumption, and
                     luminous efficiency~\\cite{aube2013}.", 
                     label = "tab:lamps"), 
      size="footnotesize", # Change size; useful for bigger tables
      include.rownames=TRUE, 
      include.colnames=TRUE, 
      caption.placement="top",
      type = "latex",
      booktabs = TRUE
      )
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Results (Zeke and Emmanuel, 2000 words)}
\label{sec:results}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% This section may be divided by subheadings.
% It should provide a concise and precise description of
% the experimental results,
% their interpretation as well as the experimental conclusions that can be drawn.
% \begin{quote}
% This section may be divided by subheadings.
% It should provide a concise and precise description of the experimental results,
% their interpretation as well as the experimental conclusions that can be drawn.
% \end{quote}

%++++++++++++++++++++++++++++++
\subsection{The effect of the exergy-to-energy ratio ($\phi_{L,\lambda}$)}
\label{sec:effect_of_phi_L}
%++++++++++++++++++++++++++++++

To illustrate the effect of the exergy-to-energy ratio for EM radiation~($\phi_{L,\lambda}$), 
the top-left graph in Figure~\ref{fig:wfs_and_lamps} shows 
Equation~\ref{eq:phi_L_lambda_shan_zhou}.
Note that exergy-to-exergy ratio for light~($\phi_{L,\lambda}$) is
nearly~1 for all wavelengths of interest for illumination.
(All graphs were constructed and calculations were performed using \texttt{R}~\cite{R-software}.)

Applying Equation~\ref{eq:phi_L_lambda_shan_zhou} 
to the four lamps identified in Section~\ref{sec:lamps}
gives the four graphs in the top-right of Figure~\ref{fig:wfs_and_lamps},
radiant power~($\Phi_{EM,\lambda}$) as a function of wavelength ($\lambda$) (spectral power distribution).
The gray regions show spectral power distributions for each lamp, and 
the dark green line indicates exergy.
The areas of the gray regions ($\Phi_{EM}$) are given by Equation~\ref{eq:emissive_power}.
The areas beneath the dark green lines in all graphs are the exergy of light~($\dot{X}_L$), 
given by Equation~\ref{eq:X_dot_L}.

Note that exergy (solid dark green line) is very close to energy (top of the gray region), because
the exergy-to-energy ratio ($\phi_{L,\lambda}$) is always close to~1 for EM wavelengths relevant to light.
The difference between energy and exergy is greatest in the upper right of the graphs when both
%
\begin{enumerate*}[label={(\alph*)}]
	
  \item emission is greater and
  
  \item wavelength is longer.
    
\end{enumerate*}


%++++++++++++++++++++++++++++++
\subsection{The effect of weighting functions ($f_\lambda$)}
\label{sec:effect_weighting_functions}
%++++++++++++++++++++++++++++++

Figure~\ref{fig:wfs_and_lamps} provides visual representation of the spectral energy and exergy of light
for the four lamps and four weighting functions of 
Sections~\ref{sec:weighting_functions} and~\ref{sec:lamps}
and Tables~\ref{tab:wfs} and~\ref{tab:lamps}, respectively.
The left column of Figure~\ref{fig:wfs_and_lamps} contains graphs of
the four weighting functions~($f_\lambda$).
Each rainbow colored region shows the light content of EM radiation (spectral luminous power) and
is the spectral product of its row's weighting function and its column's lamp spectral power distribution.
The areas of the rainbow colored regions ($\dot{L}$) are given by Equation~\ref{eq:weighted_emissive_power}.
The areas beneath the dark green lines ($\dot{X}_L$) in all graphs are given by 
Equation~\ref{eq:X_dot_L}.

\begin{figure}
    \centering
    \begin{subfigure}[t]{0.25\textwidth}
<<phi_L_lambda_vs_lambda, cache=use_cache, fig.width=1.5, fig.height=1.63>>=
tibble::tibble(lambda = seq(250, 900, by = 0.5)*10^(-9)) %>% 
  dplyr::mutate(
    T_0 = 310,
    T_lambda = 5.33016e-3 / lambda, 
    phi_L_lambda = 1 - (4/3)*(T_0/T_lambda) + (1/3)*(T_0/T_lambda)^4, 
    facet = " "
  ) %>% 
  ggplot2::ggplot(mapping = aes(x = lambda*10^(9), y = phi_L_lambda)) + 
  geom_vline(xintercept = 555, size = 0.2, color = "darkgray") +
  geom_line(linetype = 1, color = "darkgreen") + 
  scale_x_continuous(limits = c(250, 900.01), breaks = c(250, 380, 555, 750, 900)) +
  scale_y_continuous(limits = c(0.9, 1.0), breaks = c(0.9, 0.95, 1)) +
  # xlab(expression(lambda*" [nm]")) +
  xlab(element_blank()) +
  ylab(expression(phi[L*","*lambda]*" [-]")) +
  facet_grid(~facet) +
  MKHthemes::xy_theme() +
  theme(axis.text.x = element_text(size = rel(0.8), angle = 90),
        axis.text.y = element_text(size = rel(0.8)), 
        strip.text.x = element_text(margin = margin(b = 2.0)))
@
      \label{fig:phi_light_graph}
    \end{subfigure}
    % add desired spacing between images (e.g., ~, \quad, \qquad, \hfill, etc.)
    % or a blank line to force the subfigure onto a new line.
    \begin{subfigure}[t]{0.74\textwidth}
<<Energy_and_exergy_graph, cache=use_cache, fig.width=4.5, fig.height=1.63, fig.align="right">>=
response_data %>% 
  dplyr::filter(wf_name == "Unweighted") %>% 
  dplyr::mutate(
    facet = " "
  ) %>% 
  ggplot(mapping = aes(x = `Wavelength [nm]`)) +
  geom_area(mapping = aes(y = normalised_awrp), fill = "darkgray") +
  geom_line(mapping = aes(y = normalised_awe), linetype = 1, colour = "darkgreen", size = 0.1) +
  xlab(element_blank()) +
  ylab(expression(Phi["EM,"*lambda]*" [W/nm]")) +
  scale_x_continuous(limits = c(250, 900), breaks = c(250, 380, 555, 750, 900)) +
  #scale_y_continuous(limits = c(-0.002, 0.024), breaks = c(0, 0.005, 0.010, 0.015, 0.020)) +
  labs(fill = element_blank(), colour = element_blank()) +
  facet_grid(facet~lamp_name) +

  MKHthemes::xy_theme() +
  theme(axis.text.x = element_text(size = rel(0.8), angle = 90),
        axis.text.y = element_text(size = rel(0.8)),
        # Move the facet labels out of the graphs slightly.
        strip.text.y = element_text(margin = margin(l = 2.3)))
@
      \label{fig:lamp_exergy}
    \end{subfigure}
    \begin{subfigure}[t]{0.25\textwidth}
<<Weighting_Function_Graph_Energy, cache=use_cache, fig.width=1.5, fig.height=5>>=
response_data %>%
  dplyr::select("Wavelength [nm]", "normalized_response", "wf_name") %>%
  dplyr::mutate(
    header = "Wght. Func.",
    # Get nice tails at 0.
    normalized_response = tidyr::replace_na(normalized_response, 0)
  ) %>%
  ggplot(mapping = aes(x = `Wavelength [nm]`)) +
  geom_line(mapping = aes(y = normalized_response), color = "darkgray") +
  geom_vline(xintercept = 555, size = 0.2, color = "darkgray") +
  geom_line(mapping = aes(y = normalized_response)) +

  facet_grid(rows = vars(wf_name), cols = vars(header)) +
  xlab(expression(lambda*" [nm]")) +
  ylab(expression(f[lambda]*" [W/nm]")) +
  scale_x_continuous(limits = c(250, 900), breaks = c(250, 380, 555, 750, 900)) +
  #scale_y_continuous(breaks = c(0, 0.5, 1)) +
  MKHthemes::xy_theme() +
  theme(strip.text.x = element_text(margin = margin(b = 2.0)),
        # Eliminate labels on right facet. Pick up from lamp radiative powers.
        strip.text.y = element_blank(),
        axis.text.x = element_text(size = rel(0.8), angle = 90),
        axis.text.y = element_text(size = rel(0.8)))
@
        \label{fig:weighting_functions}
    \end{subfigure}
    % add desired spacing between images (e.g., ~, \quad, \qquad, \hfill, etc.)
    % or a blank line to force the subfigure onto a new line.
    \begin{subfigure}[t]{0.74\textwidth}
<<Responses_Graph_Energy, cache=use_cache, fig.width=4.5, fig.height=5, fig.align="right">>=
response_data %>%
  ggplot(mapping = aes(x = `Wavelength [nm]`)) +
  # geom_area(mapping = aes(y = actual_radiant_power), fill = "darkgray") +
  ggspectra::stat_color(mapping = aes(y = normalised_awrp),
                        geom = "bar",
                        chroma.type = chroma_type,
                        size = 0) +   # Eliminates borders
  scale_fill_identity() +
  scale_color_identity() +

  geom_line(mapping = aes(y = normalised_awe), linetype = 1, colour = "darkgreen", size = 0.1) +

  xlab(expression(lambda*" [nm]")) +
  # ylab(expression("Spectral radiative energy, "*Phi*" [W/nm]")) +
  ylab(expression(Phi[L*","*lambda]* " [W/nm]")) +
  scale_x_continuous(limits = c(250, 900), breaks = c(250, 380, 555, 750, 900)) +
  #scale_y_continuous(limits = c(-0.002, 0.022)) +
  labs(fill = element_blank(), colour = element_blank()) +
  facet_grid(rows = vars(wf_name), cols = vars(lamp_name)) +
  MKHthemes::xy_theme() +
  theme(axis.text.x = element_text(size = rel(0.8), angle = 90),
        axis.text.y = element_text(size = rel(0.8)),
        # Move the facet labels out of the graphs slightly.
        strip.text.x = element_text(margin = margin(b = 2.0)),
        strip.text.y = element_text(margin = margin(l = 2.0)))
@
        \label{fig:lamp_responses}
    \end{subfigure}
    \caption{Upper left: The spectral exergy-to-energy ratio of light~($\phi_{L,\lambda}$) 
                         from Equation~\ref{eq:phi_L_lambda_shan_zhou}. 
             Top: Gray regions indicate spectral radiant power ($\Phi_{EM,\lambda}$)
                  for lamps in Table~\ref{tab:lamps}.
                  Dark green lines show spectral exergy.
             Left: Spectral weighting functions ($f_\lambda$), as shown in Table~\ref{tab:wfs}.
             Lower right: Rainbow-colored regions indicate the human perception of color, 
                          and the portion of light deemed valuable for human perception.
                          The spectral luminous power~($\Phi_{E or L,\lambda,pl}$) 
                          is shown in the third row, 
                          by application of the Photopic luminsoity function.
                          Dark green lines show spectral exergy of light. 
             All data is normalized to 1 to correct for variation in 
             electricity consumption between lamps, and therefore radiant power, 
             along with the shape of different lamps spectral power distributions.}
             
	\label{fig:wfs_and_lamps}
\end{figure}


<<results_etas_table, cache=use_cache, results="asis", cache.extra.2=tools::md5sum('Data/results_etas_xtable.R')>>=
source("Data/results_etas_xtable.R")

print(xtable::xtable(results_etas_fin, digits=2, 
                     caption = "Final to useful energy efficiencies
                     ($\\eta_{E,f_{\\lambda}}$, in \\%) for each lamp
                     and weighting function~($f_\\lambda$)
                     given by Equation~\\ref{eq:eta_E_v_light}.
                     Note that for the incandescent bulb (INC), 
                     the unweighted final to useful efficiency is an 
                     underestimate, 
                     because the SPD data were limited to $\\lambda < \\text{899 nm}$, 
                     despite INC emission far into 
                     the infrared region of the EM spectrum.", 
                     label= "tab:results_etas"), 
      size="footnotesize", # Change size; useful for bigger tables
      include.rownames=TRUE, 
      include.colnames=TRUE, 
      caption.placement="top",
      type = "latex",
      booktabs = TRUE,
      sanitize.rownames.function = identity
      )
@

<<results_phi_table, cache=use_cache, results="asis", cache.extra.2=tools::md5sum('Data/results_phi_xtable.R')>>=
source("Data/results_phi_xtable.R")

print(xtable::xtable(results_phi_fin, digits=3, 
                     caption = "Exergy to energy ratios~($\\phi_{f_{\\lambda}}$) 
                     for each lamp, 
                     and each weighting function ($f_{\\lambda}$), 
                     given by Equation~\\ref{eq:phi_L}.", 
                     label= "tab:results_phis"), 
      size="footnotesize", #Change size; useful for bigger tables
      include.rownames=TRUE, 
      include.colnames=TRUE, 
      caption.placement="top",
      type = "latex",
      booktabs = TRUE,
      sanitize.rownames.function = identity
      )
@


<<results_etasX_table, cache=use_cache, results="asis", cache.extra.2=tools::md5sum('Data/results_etasX_xtable.R')>>=
source("Data/results_etasX_xtable.R")

print(xtable::xtable(results_etasX_fin, digits=2, 
                     caption = "Final to useful exergy efficiencies
                     ($\\eta_{X,f_{\\lambda}}$, in \\%) for each lamp
                     and weighting function~($f_\\lambda$)
                     given by Equation~\\ref{eq:eta_X_v_light}.", 
                     label= "tab:results_etasX"), 
      size="footnotesize", # Change size; useful for bigger tables
      include.rownames=TRUE, 
      include.colnames=TRUE, 
      caption.placement="top",
      type = "latex",
      booktabs = TRUE,
      sanitize.rownames.function = identity
      )
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Discussion (ZM, MKH 1000 words)}
\label{sec:discussion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Authors should discuss the results and how they can be interpreted
in perspective of previous studies and of the working hypotheses.
The findings and their implications should be discussed
in the broadest context possible.
Future research directions may also be highlighted.


****
ZM and PB: Be sure to spike the set from the introduction.
****



****
ZM: Discuss how our results for the examples vary from results that would have been obtained with
previous methods of determining the exergy of lighting.
****



%++++++++++++++++++++++++++++++
\subsection{Comparison with previous approach to calculating $\eta_{X,v}$ in societal exergy analysis}
\label{sec:compwithSEA}
%++++++++++++++++++++++++++++++

The calculation of the exergy of light presented in Section~\ref{sec:phi_light}
differs from the previous approach used in the societal exergy analysis community.
This section describes the previous approximate approach 
and compares to the new exact approach presented in Section~\ref{sec:framework}.


%------------------------------
\subsubsection{Approximate method} 
\label{sec:previous_approach}
%------------------------------

In societal exergy analysis, exergy calculations are sometimes hampered when 
``the useful output cannot or is not typically measured in energy units''
\cite[p.~17]{Sousa2017}. 
In these circumstances, researchers in societal exergy analysis approximate
exergetic efficiency by the quotient of
the minimum energy required to produce a given output and
the actual energy required to produce the same given output.
(See Section~\ref{sec:divergent_approaches}.)
The approximate approach has been recommended
for lighting, sound, and information~\cite[p.~17]{Sousa2017}.

For the specific case of lighting,
the approximate method involves the quotient of
the theoretical minimum rate of energy required to emit one lumen and
the actual rate of energy used to emit one lumen 
for a given lamp.
The minimum and actual energy rates are obtained 
by taking the inverses of luminous efficacy~($K$).
For a lamp, the quotient is between the lamp's luminous efficacy~($K$)
and the maximum luminous efficacy~($K_{max}$).
%
\begin{equation} \label{eq:K_over_e_max}
  \eta_{E,v,pl} = \frac{\; \; \frac{1}{K_{max}} \; \; }{\frac{1}{K}}
       = \frac{K}{K_{max}} \; .
\end{equation}

Equation~\ref{eq:lum_effic_def} shows that 
the luminous efficacy of a lamp~($K$) is equal to the quotient
of the luminous power ($\Phi_{pl}$, Equation~\ref{eq:lumen}), expressed in lumens, and
the electricity consumption rate of the device
($\dot{W}_1$ in Figure~\ref{fig:lamp}).
Substituting Equation~\ref{eq:lum_effic_def} into Equation~\ref{eq:K_over_e_max} gives
(with reference to Figure~\ref{fig:lamp})
exergetic efficiency for the approximate method:
%
\begin{equation} \label{eq:prev_eta_X_v_light}
  \eta_{E,v,pl} = \frac{\; \; \frac{(683 \text{ lm/W}) \int V_\lambda \Phi_{EM,\lambda,3} \mathrm{d}\lambda}{\dot{W}_1} \; \;}{K_{max}} \; .
\end{equation}

**** We need a unique symbol for this equation, the \emph{luminous efficiency}.
We can say it is equivalent to $\eta_{E,v,pl}$, 
but this is currently the symbol for the final-useful efficiency 
for our method as detailed above ---ZM ****

With recent advances in photometry (Section~\ref{sec:phi_light}),
it is now possible to determine the energy and exergy of light exactly, 
thereby relieving societal exergy analysts
of the need to approximate exergetic efficiency
by the quotient of
the minimum energy required to produce a lumen and
the actual energy required to produce a lumen.
Thus, we can evaluate the approximate method in light of recent advances, 
using exergetic efficiency as the point of comparison.

Comparing Equation~\ref{eq:prev_eta_X_v_light} (the approximate method)
to Equation~\ref{eq:eta_X_v_light} (the exact method)
reveals that the approximate method for calculating the exergetic efficiency of lighting
is correct only under the following conditions:
%
\begin{enumerate}[label={(\alph*)}]
	
  \item $\phi_{L,\lambda} = 1$,

  \item the maximum luminous efficacy ($K_{max}$) is assumed to be 683~lm/W, and 
  
  \item the spectral weighting function is taken to be the photopic luminosity function ($f_\lambda = V_\lambda$).

\end{enumerate}

As can be seen by comparing the luminous efficiency row of Table~\ref{tab:lamps} 
and the photopic luminosity row of Table~\ref{tab:results_etas},
final-to-useful efficiencies calculated using the photopic luminosity function~($\eta_{E,v,pl}$, Equation \ref{eq:eta_E_v_light} (with $f_\lambda = V_\lambda$))
are equivalent to luminous efficiency values
~($\eta_{E,v,pl}$, Equation~\ref{eq:prev_eta_X_v_light}) 
when maximum luminous efficacy~($K_{max}$) is taken to be 683~lm/W.


%------------------------------
\subsubsection{Implications for societal exergy analysis} 
\label{sec:implications_for_sea}
%------------------------------

The above comparison between the previous approximate method and
the new exact method of Section~\ref{sec:light_efficiency}
raises three implications for societal exergy analysis.
First, to obtain the correct exergetic efficiency of lighting, 
analysts must reject the assumption of the previous approximate method that $\phi_{L,\lambda} = 1$.
Recent progress in photometry enables this rejection, 
following the methods of Section~\ref{sec:phi_light}.
Specifically, the spectral exergy-to-energy ratio of light ($\phi_{L,\lambda}$)
of Equation~\ref{eq:phi_L_lambda_shan_zhou} and Figure~\ref{fig:wfs_and_lamps} should be used.
We note, however, that $\phi_{L,\lambda}$ is close to~1 for all wavelengths of interest to illumination.
Happily, the previous approximate method was not far wrong.

Second, with the previous approximate method, 
the analyst was required to select a value for maximum luminous efficacy ($K_{max}$), 
the denominator of Equation~\ref{eq:prev_eta_X_v_light}.
The choice of $K_{max}$ can make a significant difference to the results.
For example, \citet{Ayres2005} and \citet{Guevara2016}
assume $K_{max} = 400 \text{ lm/W}$,
thereby incorrectly overestimating exergetic lighting efficiency~($\eta_{X,v}$)
by a factor of $\frac{683 \text{ lm/W}}{400 \text{ lm/W}} = 1.71$.

Third, in the approximate method, 
the analyst was required to use the photopic luminosity function~($V_\lambda$)
for the specular weighting function~($f_\lambda$).
However, it is not certain that the photopic luminosity function
is the best choice, 
as discussed in Section~\ref{sec:blue_light} below.

In summary, the exact method provides the following benefits:
%
\begin{enumerate}[label={(\alph*)}]
	
  \item it uses the correct spectral exergy-to-energy ratio~($\phi_{L,\lambda}$), no longer assuming its value to be~1;

  \item it is free of (possibly erroneous) assumptions for the maximum luminous efficacy ($K_{max}$); and 
  
  \item it allows choices for the spectral weighting function~($f_\lambda$), 
        no longer requiring $f_\lambda = V_\lambda$, 
        thereby enabling analyses suited precisely to each application of EM radiation
        (illumination, human physiology, photosynthesis for horticulture, etc.).

\end{enumerate}


****
Discuss how to apply our method in a SEA context.
Is our method applicable with data usually available to an analyst?---EAR
****

****
EAR: Our method is not readily applicable to the SEA analyst as it requires SPD data on each lamp,
or at least lighting technology used in that country, and over time.
However, we can state that if the analyst deems that light is most useful at 555nm, and chooses to apply the photopic luminosity function the equation $\eta = \frac{K}{K_{max}}$ is equivalent to our approach if $K_{max} = 683 lm/W$
We could offer an average $\phi$ value to replace $\phi_{\lambda}$ in order to move from energy to exergy, and even a factor to move from $\Phi_{pl}$ to $\Phi_{EM}$. This might be something to discuss at our next meeting ---ZM
****


****
By how much would SEA results change if we adopt this new methodology?
I.e. how wrong were former studies and how critical is it to improve the methodology?---EAR
****

****
How wrong previous studies were depends on what we feel the correct approach to be. 
I think we should decide this as a group, and then we can quantify the difference! ---ZM
****


%++++++++++++++++++++++++++++++
\subsection{Weighting functions and blue light}
\label{sec:blue_light}
%++++++++++++++++++++++++++++++

Previously, societal exergy analysis implicitly adopted the photopic luminosity function~($V_\lambda$)
when calculating the exergetic efficiency of lighting.
(See Section~\ref{sec:previous_approach}.)

Given that the industry-standard measure of lighting efficiency
is the luminous efficacy~($K$),
the use of the photopic luminosity function~($V_\lambda$)
under-represents the power at short wavelengths in lighting efficiency estimates.
This state of affairs biases lighting manufacturers to reduce short wavelength
output of lamps, even when short wavelength EM radiation would be beneficial
for physiological reasons such as the suppression of melanopsin 
the regulation of circadian rhythms \cite{Pattison2018LEDphotons}.

To account for this many lamps are designed to have 'blue spike', 
emitting radiant energy in the region of 480nm, 
the peak of the melanopsin suppression action spectrum \cite{lucas2014}, 
as can be seen from the spectral power distribution~($\Phi_{EM,\lambda}$)
for the LED lamp in Figure \ref{fig:wfs_and_lamps}. 

To more accurately quantify the utility of different wavelengths of light,
the universal luminosity function has been proposed 
as a replacement for the photopic luminosity function, because it 
accounts for the sensitivity of all five of the eyes light receptors 
as discussed in Section~\ref{sec:human_perception_of_EM_radiation}.

The choice of weighting function should be made appropriate for the application of each lamp.
To provide consistency for societal exergy analysis community moving forward
we propose that societal exergy analysts 
adopt the universal luminosity function ($U_\lambda$) in accordance with \cite{Rea2018},
when lamps are used solely for illumination in society.
The switch from the photopic luminosity function~($V_\lambda$)
to the universal luminosity function~($U_\lambda$) is made possible 
by the exact method described in Section~\ref{sec:framework}. 
The approximate method requires the use of the photopic luminosity function~($V_\lambda$),
as discussed in Section~\ref{sec:previous_approach}.

**** We have still not finalised this decision. What do you all think? 
If we propose this, we need to also lay out practical steps for analysts
given that the available data is nearly always published in lm/W 
i.e an additional factor per lamp ---ZM ****
****
I'm comfortable with this recommendation.
I suggest that Zeke write another paragraph here that discusses the difference in exergetic efficiency
between using $V_\lambda$ and $U_\lambda$.
Use Table~\ref{tab:results_etas}.---MKH
****


%++++++++++++++++++++++++++++++
\subsection{Further challenges}
\label{sec:further_challenges}
%++++++++++++++++++++++++++++++

There are two challenges facing the societal exergy analyst regarding
the exergy of light, namely
%
\begin{enumerate*}[label={(\alph*)}]

  \item how to account for waste heat from lamps and
  
  \item how to account for waste light from lamps.

\end{enumerate*}
%
We discuss each challenge in the sections below.


%------------------------------
\subsubsection{Waste heat from lamps}
\label{sec:waste_heat}
%------------------------------

Every lamp produces waste heat ($\dot{Q}_2$ in Figure~\ref{fig:lamp})
as it converts electrical energy into light energy. 
The efficiency describing this process is often referred to as the \emph{first law efficiency} or \emph{wall plug efficiency}.
In this analysis the proportion of heat generated by a lamp is given by 
$1-\eta_{i,uw}$ or $1-\frac{\Phi_{i,uw}}{\dot{W}_{1}}$.


**** Shall we report the proportion of heat, and IR radiation that a lamp generates 
in an additional results table? ---ZM ****


In Section~\ref{sec:energy_and_exergy_of_light}
waste heat was deemed the un-valuable product of the lamp.
However, in some circumstances, the waste heat from lamps is, in fact, valuable,
because it displaces energy for space heating,
especially in winter climates.
In summer climates, waste heat from lamps adds to space cooling loads.
For locations where both summer cooling and winter heating are performed,
the winter/summer effects of lamps cancel, to first order.

The societal exergy analyst must decide how to treat waste heat from lamps
when determining the quantity of useful energy delivered to a society.
To our knowledge, societal exergy analysis has, to date,
ignored waste heat from lamps,
implicitly assuming that winter and summer effects cancel.
We contend that the issue deserves further study,
but that is a topic for another paper.

In addition to the thermal heat generated by a lamp, 
some lamps, commonly termed heat lamps, infrared lamps or infrared heaters are
explicitly designed to produce radiative heat 
(light in the form of near and far infrared radiation) 
for various purposes, including
space heating, incubator heating, plastic manufacture, 
food preparation, and warming animals in captivity.

As the infrared portion of light emitted as radiative heat is considered useful 
common ceramic infrared heaters have final to useful energy efficiencies of 56.7~\% \cite{brown2016} when emitting radiative heat,
with the remainder of the energy (43.3~\%) converted into thermal heat, 
which may or may not be considered useful 
as the mechanism of thermal heat transfer acts over a shorter distance (convection).

**** Shall we outine the three mechanisms of heat transfer above, namely: thermal radiation/radiative heat, convection and conduction? ---ZM ****

In the framework presented in this study

%------------------------------
\subsubsection{Waste light from lamps (MKH and ZM)}
\label{sec:waste_light}
%------------------------------

In the exact method of this study,
light is considered wasted if it either outside of the range of wavelengths
in a spectral weighting function~($f_\lambda$), or
within a wavelength of light for which the radiant power has been reduced as a result of a weighting function.
The portion of light not wasted is termed the valuable light ($\Phi_v$).

This mechanism is discussed in Section~\ref{sec:effect_weighting_functions}.

However, our framework assumes that all of the valuable light emitted by a lamp is utilised. 
Two further losses occur before the valuable light is available for work \cite{CullenPhD}.
%
\begin{enumerate}[label={(\alph*)}]

  \item Losses within the luminaire (lamp housing) - 
        where a proportion of light never exits the device.
   
  \item Light which is incident upon surfaces which do not need to be illuminated
        such as ceilings. Together with luminaire losses, 
        this is quantified by the luminaire output ratio.

\end{enumerate}
%
Furthermore, there are three additional passive losses of light, as detailed by \citet{CullenPhD}.
%
\begin{enumerate}[label={(\alph*)}]

  \item Light which is emitted with an excessive intensity.
   
  \item Light which is incident upon surfaces which are not the primary purpose of illumination.
  
  \item Light which is under-utilised, e.g. through under-occupancy.
       

\end{enumerate}
%

Accounting for all of these potential efficiency savings in a commercial office lighting scenario
\citet{CullenPhD} estimates the upper limit for energy savings to be 95~\%.

**** I need to look at a broader range of literature than Cullen (2010) ---ZM ****

In the context of SEA, and the energy conversion chain, 
these losses occur at the \emph{energy service} stage, 
after the conversion of electricity to radiant power or light. 
As such we deem further analysis of these passive efficiency losses 
beyond the scope of our study.



%++++++++++++++++++++++++++++++
\subsection{Application for country-level societal exergy analysis}
\label{sec:Application}
%++++++++++++++++++++++++++++++

To move from the final to useful energy/exergy efficiency of a single lamp, 
to either an economy-wide or sectoral aggregate lighting efficiency, 
several types of data are required for the given period of study:

\begin{enumerate}[label={(\alph*)}]

  \item Final to useful efficiency data for each lamp technology
  \item Energy to exergy ratios for each of the corresponding lamp technologies
  \item Electricity consumption by lamp technology

\end{enumerate}

Items $a$ and $b$ are rarely reported for lamps, nor is the associated SPD data.
Instead the most common measure of lighting efficiency reported for lamps is the luminous efficacy.
Therefore, to develop an aggregate measure of lighting efficiency, 
luminous efficacy data must be converted into final to useful efficiency values.
As demonstrated in Section~\ref{sec:previous_approach} if the \emph{valuable} light
is deemed to be the radiant power weighted by the photopic luminosity function 
(luminous power, $\Phi_{pl}$),
the final to useful efficiencies are equivalent to the luminous efficiency, 
namely $\frac{K}{683 lm/W}$.
In the absence of SPD data an exergy to energy ratio for each technology type must be selected,
as the shape of lamp SPD's display relatively little variation within technology groups
compared to between groups, 
the aggregate exergy to energy ratios for those lamps also display little variation.

**** Shall i calculate phi for several types of the same type to demonstrate this? ---ZM ****

**** Do we provide factors to move from $\Phi_{EM,i,pl}$ to $\Phi_{EM,i,?}$ ---ZM ****

Once efficiency series have been calculated
and exergy to energy ratios obtained for each lamp type,
data for the proportion of each lamp type in use for each year of the study is needed,
i.e. the fleet of lamps, 
and ideally in the form of electricity consumption by lighting technology.
For example, tHe US DOE's Lighting Market Characterization reports provide such data for the USA,
and for the years 2001~\cite{DOE2002}, 2010~\cite{DOE2012}, and 2015~\cite{DOE2017}, 
along with associated luminous efficacy values, 
and for the following lamp technologies: incandescent, halogen, compact fluorescent,
linear fluorescent, high intensity discharge, LED and other.

The aggregate lighting efficiency for a particular year is then given by

\begin{equation} \label{eq:agg_eta}
  \eta_{agg} = \sum \limits_{i \in Lamps} \theta_{i,pl} \cdot \phi_{i,pl} \cdot \eta_{E,i,pl} 
\end{equation}

Where $\theta_{i}$ denotes the proportion of electricity consumption for lighting
by a particular lamp technology for a given year.

**** Do we provide a demonstration using the DOE data? 
e.g. "for which we provide the concise following example........" ---ZM ****


Doing this work is beyond the scope of this paper.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Summary (MKH, 500 words)}
\label{sec:conclusions}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% This section is not mandatory, but can be added to the manuscript if the discussion is unusually long or complex.

****
MKH: Recommend using our method for SEA going forward.
****


****
MKH: Include a future work section.
Do we want to include something about waste heat from lamps?
****



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\vspace{6pt} 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\supplementary{The datasets associated with this paper are available online (https://doi.org/10.5518/865) \cite{heun2020}

**** The following are available online at \linksupplementary{s1}, Figure S1: title, Table S1: title, Video S1: title. ****}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\authorcontributions{For research articles with several authors, 
a short paragraph specifying their individual contributions must be provided. 
The following statements should be used:

Conceptualization, X.X. and Y.Y.; 
methodology, X.X.; 
software, X.X.; 
validation, X.X., Y.Y. and Z.Z.; 
formal analysis, X.X.; 
investigation, X.X.; 
resources, X.X.; 
data curation, X.X.; 
writing--original draft preparation, X.X.; 
writing--review and editing, X.X.; 
visualization, X.X.; 
supervision, X.X.; 
project administration, X.X.; 
funding acquisition, Y.Y.
All authors have read and agreed to the published version of the manuscript.

Please turn to the  \href{http://img.mdpi.org/data/contributor-role-instruction.pdf}{CRediT taxonomy} for the term explanation. Authorship must be limited to those who have contributed substantially to the work reported.}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\funding{Please add: 
``This research received no external funding'' or 
``This research was funded by NAME OF FUNDER grant number XXX.'' and  and 
``The APC was funded by XXX''.
Check carefully that the details given are accurate and
use the standard spelling of funding agency names at
\url{https://search.crossref.org/funding},
any errors may affect your future funding.}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\acknowledgments{We would like to thank James D. Hooker for the use of data from the Museum of Electric Lamp Technology ~\cite{hooker_2020}, Alfonso Delgado-Bonal for his advice on the state of the discourse regarding the exergy to energy factor of light, Pedro J. Aphalo for his open-source software suite ‘r4phototbiology’~\cite{Aphalo2015}, Martin Aubé and Johanne Roby for the use of their Light Spectral Power Distribution Database (LSPDD)~\cite{aube2013}, Micheal Royer for his advice regarding photometric data,.......  }


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\conflictsofinterest{The authors declare no conflict of interest. 
The funders had no role in the design of the study; 
in the collection, analyses, or interpretation of data; 
in the writing of the manuscript; or 
in the decision to publish the results.} 





%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Nomenclature}
\label{sec:nomenclature}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/nomenclature.tex}

**** I think we need to get rid of the subscript L. 
             We currently use this to denote light, 
             but what we deem light is a function of a particular weighting function 
             which we should always specify in the subscript in all of our metrics. 
             We should also always specify whether the radiant power is in energy ($E$)
             or exergy ($X$) terms.
             
             As i have done for the etas the radiant power should be denoted as follows:
             ($\Phi_{E or X, f_{\lambda}}$)
             
             and the spectral radiant power should be denoted as follows
             ($\Phi_{E or X,\lambda, f_{\lambda}}$)
        
             If we keep L we should make it clear that this is a special case 
             for the photopic luminosity function only, 
             however I don't think we should, 
             its easy enough for the reader to see the subscript $pl$! ---ZM ****


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% optional
\appendixtitles{yes} 
% Leave argument "no" 
% if all appendix headings stay EMPTY
% (then no dot is printed after "Appendix A").
% If the appendix sections contain a heading then change the argument to "yes".


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\appendix

% \input{pieces/appendix.tex}

<<test, child='pieces/appendix.Rnw'>>=
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\reftitle{References}

% Please provide either the correct journal abbreviation (e.g. according to the 
% “List of Title Word Abbreviations” http://www.issn.org/services/online-services/access-to-the-ltwa/) or 
% the full name of the journal.
% Citations and References in Supplementary files are permitted provided that they also appear in the reference list here. 


%=====================================
% References, variant A: external bibliography
%=====================================
\externalbibliography{yes}
\bibliography{LightingPaper2020}


%=====================================
% References, variant B: internal bibliography
%=====================================
% \begin{thebibliography}{999}
% % Reference 1
% \bibitem[Author1(year)]{ref-journal}
% Author1, T. The title of the cited article. {\em Journal Abbreviation} {\bf 2008}, {\em 10}, 142--149.
% % Reference 2
% \bibitem[Author2(year)]{ref-book}
% Author2, L. The title of the cited contribution. In {\em The Book Title}; Editor1, F., Editor2, A., Eds.; Publishing House: City, Country, 2007; pp. 32--58.
% \end{thebibliography}

% To cite two works by the same author: \citeauthor{ref-journal-1a} (\citeyear{ref-journal-1a}, \citeyear{ref-journal-1b}). This produces: Whittaker (1967, 1975)

% To cite two works by the same author with specific pages: \citeauthor{ref-journal-3a} (\citeyear{ref-journal-3a}, p. 328; \citeyear{ref-journal-3b}, p.475). This produces: Wong (1999, p. 328; 2000, p. 475)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% optional
% \sampleavailability{Samples of the compounds ...... are available from the authors.}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{document}

